version: "3"
services:
  electron-builder:
    image: electronuserland/builder:wine
    volumes:
      - "$PWD:/project"
      # - "node_modules:/project/node_modules"
    command: yarn compile && yarn dist
volumes:
  node_modules:
